### PR TITLE
Restore using latest cassandra image for CI

### LINKED ISSUE #280: Adjust test cases to Cassandra 4
Part of our continuous integration process is running all the test cases against a cassandra instance. Unfortunately, the recent release of Cassandra 4 broke some of the date type tests:
```
failures:

---- frame::cql_types_test::test_date stdout ----
Connecting to 127.0.0.1:9042 ...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DbError(Invalid, "Unable to coerce '5881580-07-11' to a formatted date (long)")', scylla/src/frame/cql_types_test.rs:314:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- frame::cql_types_test::test_naive_date stdout ----
Connecting to 127.0.0.1:9042 ...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DbError(Invalid, "Unable to coerce '0000-1-1' to a formatted date (long)")', scylla/src/frame/cql_types_test.rs:232:14


failures:
    frame::cql_types_test::test_date
    frame::cql_types_test::test_naive_date

test result: FAILED. 137 passed; 2 failed; 1 ignored; 0 measured; 0 filtered out; finished in 4.55s
```

A quick workaround is to set Cassandra version in our CI to 3.11.11, but in the long term we should restore operability on Cassandra 4 and go back to using the latest release.

### PR DESCRIPTION
**Pull request by psarna**
- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] I added relevant tests for new features and bug fixes.
- [x] All commits compile, pass static checks and pass test.
- [x] PR description sums up the changes and reasons why they should be introduced.
- [x] I added appropriate `Fixes:` annotations to PR description.

This series amends the test to work with Cassandra 4 and drops the workaround in our continuous integration, which used Cassandra 3.11 until the issues were resolved.

Fixes #280

### CODE REVIEW

File: scylla/src/frame/cql_types_test.rs [hunk 1]
```diff
@@ -205,20 +205,23 @@ async fn test_naive_date() {
...
+
         // 1 less/more than min/max values allowed by NaiveDate
         ("-262145-12-31", None),
-        ("262144-1-1", None),
+        // NOTICE: dropped for Cassandra 4 compatibility
+        //("262144-01-01", None),
         // min/max values allowed by the database
         ("-5877641-06-23", None),
-        ("5881580-07-11", None),
+        //("5881580-12-31", None),
```
Comment (piodul) [inline scylla/src/frame/cql_types_test.rs:224]: Why change the day and month if you are going to comment it out?

File: scylla/src/frame/cql_types_test.rs [hunk 2]
```diff
@@ -205,20 +205,23 @@ async fn test_naive_date() {
...
         ("2020-03-07", Some(NaiveDate::from_ymd(2020, 3, 7))),
-        ("1337-4-5", Some(NaiveDate::from_ymd(1337, 4, 5))),
-        ("-1-12-31", Some(NaiveDate::from_ymd(-1, 12, 31))),
+        ("1337-04-05", Some(NaiveDate::from_ymd(1337, 4, 5))),
+        ("-0001-12-31", Some(NaiveDate::from_ymd(-1, 12, 31))),
         // min/max values allowed by NaiveDate
-        ("-262144-1-1", Some(min_naive_date)),
-        ("262143-12-31", Some(max_naive_date)),
+        // NOTICE: dropped for Cassandra 4 compatibility
+        //("-262144-1-1", Some(min_naive_date)),
```
[the remark this answers is not in the document]
Comment (psarna) [reply scylla/src/frame/cql_types_test.rs:215]: Oh, it is, but for a different reason, which is fixable. I'll change to `-262144-01-01` and it will work, thanks.

File: scylla/src/frame/cql_types_test.rs (hunk 1 above)
Comment (psarna) [reply scylla/src/frame/cql_types_test.rs:224]: leftovers from my experiments with Cassandra 4, will revert to original values

**Review by piodul — APPROVED** [review]
